default: &default
  adapter: postgresql
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  variables:
    statement_timeout: <%= ENV.fetch("STATEMENT_TIMEOUT") { nil } %>
    idle_in_transaction_session_timeout: <%= ENV.fetch("IDLE_IN_TRANSACTION_SESSION_TIMEOUT") { nil } %>

development_primary_default: &development_primary_default
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_PRIMARY") { "weather_forecast_development" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { nil } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { nil } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  migrations_paths: db/primary

development_wf_logs_default: &development_wf_logs_default
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_WF_LOG") { "wf_logs_development" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { nil } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { nil } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  migrations_paths: db/wf_logs

development:
  primary:
    <<: *development_primary_default
  wf_logs:
    <<: *development_wf_logs_default

test:
  primary:
    <<: *development_primary_default
    database: <%= ENV.fetch("POSTGRES_TEST_DB_PRIMARY") { "weather_forecast_test" } %>
  wf_logs:
    <<: *development_wf_logs_default
    database: <%= ENV.fetch("POSTGRES_TEST_DB_WF_LOG") { "wf_logs_test" } %>



production:
  primary: &default
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  wf_logs:
    url: <%= ENV["DATABASE_URL_WF_LOGS"] %>
    migration_paths: db/wf_logs
