---
:concurrency: 5
:queues:
  - logging
  - forecasts
  - mailers
:scheduler:
  :schedule:
    fetch_forecasts:
      cron: '0 * * * *'   # Runs every hour at minute 0
      class: 'FetchForecastsJob'