name: RSpec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.6
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          LOG_NWS_REQUESTS: 1
          RAILS_MAX_THREAD: 5
          REDIS_URL: ${{ secrets.REDIS_URL }}
          TEST_PRIMARY_DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_USER }}@localhost:5432/${{ secrets.TEST_PRIMARY_DATABASE }}
          TEST_WF_LOGS_DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_USER }}@localhost:5432/${{ secrets.TEST_WF_LOGS_DATABASE }}
        run: |
          bin/rails db:setup
          bundle exec rspec
