name: RSpec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.6
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          RACK_SESSION_SECRET: ${{ secrets.RACK_SESSION_SECRET }}
          RAILS_ENV: test
          GEONAMES_USERNAME: ${{ secrets.GEONAMES_USERNAME }}
          LOG_NWS_REQUESTS: 1
          PREFIXED_IDS_SALT: ${{ secrets.PREFIXED_IDS_SALT }}
          RAILS_MAX_THREAD: 5
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SIMPLE_COV_ENABLED: ${{ secrets.SIMPLE_COV_ENABLED }}
        run: |
          bin/rails db:setup
          bundle exec rspec
